name: Build-Padavan-PSG1218_k2

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python3-docutils gettext automake autopoint texinfo build-essential \
          help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libltdl-dev wget libssl-dev

    - name: Clone Source Code
      run: |
        git clone --depth=1 https://github.com/JUST-INTJ/Padavan-KVR.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Locate and Patch Threadpool File
      run: |
        # 动态定位文件位置
        THREADPOOL_FILE=$(find /opt/rt-n56u -name "threadpool.c" | head -1)
        
        if [ -f "$THREADPOOL_FILE" ]; then
          echo "Found threadpool.c at: $THREADPOOL_FILE"
          
          # 备份原始文件
          sudo cp "$THREADPOOL_FILE" "${THREADPOOL_FILE}.bak"
          
          # 应用修复
          sudo sed -i 's/SYS_pidfd_open/__NR_pidfd_open/g' "$THREADPOOL_FILE" || true
          
          # 确保宏定义存在
          if ! grep -q "__NR_pidfd_open" "$THREADPOOL_FILE"; then
            echo "#define __NR_pidfd_open 434" | sudo tee -a "$THREADPOOL_FILE"
          fi
        else
          echo "Warning: threadpool.c not found, skipping patch"
        fi

    - name: Build Firmware
      env:
        TNAME: PSG1218
      run: |
        cd /opt/rt-n56u/trunk
        
        # 验证配置文件存在
        if [ ! -f "configs/templates/$TNAME.config" ]; then
          echo "Error: Missing config file for $TNAME"
          exit 1
        fi
        
        # 准备配置
        cp -f "configs/templates/$TNAME.config" .config
        
        # 清理构建环境
        sudo ./clear_tree
        
        # 开始构建（添加详细日志）
        echo "Starting build process..."
        sudo ./build_firmware_modify "$TNAME" 0 | tee build.log
        
        # 验证输出文件
        if ls images/*.trx >/dev/null 2>&1; then
          sudo mv -f images/*.trx /opt/images/
          echo "Build successful!"
          ls -lh /opt/images/
        else
          echo "Build failed! Log tail:"
          tail -n 50 build.log
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-binaries
        path: /opt/images/*.trx
        if-no-files-found: error
