name: Build-Padavan-PSG1218_k2

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # 升级到更新的 Ubuntu 版本
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4  # 更新到最新稳定版

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python3-docutils gettext automake autopoint texinfo build-essential \
          help2man pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev \
          libncurses5-dev libltdl-dev wget libssl-dev

    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        git clone --depth=1 https://github.com/JUST-INTJ/Padavan-KVR.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Apply kernel compatibility patch
      run: |
        # 修复 pidfd_open 兼容性问题
        sed -i 's/SYS_pidfd_open/__NR_pidfd_open/g' /opt/rt-n56u/trunk/user/msd_lite/msd_lite/src/liblcb/src/threadpool/threadpool.c || true
        # 移除不支持的编译选项
        find /opt/rt-n56u -type f -name "CMakeLists.txt" -exec sed -i 's/-Wno-unsafe-buffer-usage//g' {} \;

    - name: Build Firmware
      env:
        TNAME: PSG1218
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ]; then
          echo "Error: configs/templates/$TNAME.config not found"
          exit 1
        fi
        
        cp -f configs/templates/$TNAME.config .config
        
        # 清理之前可能存在的构建缓存
        sudo ./clear_tree
        
        # 使用更稳定的构建命令
        sudo ./build_firmware_modify $TNAME 0 || (echo "Build failed!"; exit 1)
        
        # 检查生成的固件文件
        if ls images/*.trx 1> /dev/null 2>&1; then
          sudo mkdir -p /opt/images/
          sudo mv -f images/*.trx /opt/images/
          echo "Build successful! Firmware files:"
          ls -lh /opt/images/
        else
          echo "Error: No firmware file generated!"
          exit 1
        fi

    - name: Upload packages
      uses: actions/upload-artifact@v3  # 使用稳定版本
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
